<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="KSPHP" />
	<title><?php echo APP_TITLE;?></title>
<!--	<link rel="icon" type="image/x-icon" href="https://assets-cdn.github.com/favicon.ico">-->
<!--	<link rel="icon" type="image/x-icon" href="/favicon.ico">-->
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
	<?php echo $this->tag->stylesheetLink("../webmis/themes/".WEBMIS_THEMES."/webmis.css");?>
	<?php echo $this->tag->stylesheetLink("../themes/admin/".APP_THEMES."/main.css");?>
</head>

<body class="body">
	<h1 id="webmisVersion" class="login_title">WebMIS</h1>
	<div class="login_body">
		<div class="login_ct">
			<dl class="login">
				<dt>用户名：</dt>
				<dd><input type="text" id="uname" class="input" /></dd>
				<dt>密码：</dt>
				<dd><input type="password" id="passwd" class="input" /></dd>
			</dl>
			<a href="#" id="adminLogin" class="sub">登录</a>
		</div>
	</div>
	<div class="login_copy">
		Copyright © <?php echo APP_COPY;?> All rights are reserved.<br>
		<a href="<?php echo base_url('../');?>" >网站首页</a> | <a href="?mode=pc" >电脑版</a> | <a href="?mode=mobile" >手机版</a>
	</div>
<div id="base_url" style="display: none;"><?php echo base_url();?></div>
<div id="is_mobile" style="display: none;"></div>
<?php echo $this->tag->javascriptInclude("../webmis/plugin/jquery/".JQUERY_NAME);?>
<?php echo $this->tag->javascriptInclude("../webmis/jquery.webmis.js");?>
<?php echo $this->tag->javascriptInclude("../themes/admin/".APP_THEMES."/login.js");?>
</body>
</html>