<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="KSPHP" />
	<?php echo $this->tag->getTitle();?>
	<link rel="shortcut icon" href="/themes/favicon.ico" type="image/x-icon" />
	<?php echo $this->tag->stylesheetLink("../webmis/themes/".WEBMIS_THEMES."/webmis.css");?>
	<?php echo $this->tag->stylesheetLink("../themes/admin/".APP_THEMES."/main.css");?>
</head>

<body class="top_bg">
<header class="top_ct">
	<div class="top_logo"><a href="http://www.ksphp.com" title="WebMIS" target="_blank">&nbsp;</a></div>
	<ul class="nav">
<?php foreach($Menus as $val){
	$an = $val['id']==$FID[0]?'nav_an1':'nav_an2';
	$ico = $val['ico']?'<em class="'.$val['ico'].'"></em>':'';
?>
		<li><a href="<?php echo base_url($val['url']);?>" class="<?php echo @$an;?>"><?php echo $ico.$val['title'];?></a></li>
<?php }?>
	</ul>
	<span class="top_link"><?php echo $UserInfo['uname'].'（'.$UserInfo['name'].'）';?>&nbsp;|&nbsp;<a href="<?php echo base_url('index/loginOut');?>"><b>注销</b></a></span>
</header>
<section class="ct_body">
	<aside class="ct_left">
<?php foreach (@$Menu as $val1) {if(@$val1->menus){?>
<?php foreach (@$val1->menus as $val2) {
	$an = $val2->id==$this->Cid?'left_an1':'left_an2'; 
?>
		<div class="left_title" onclick="menuTwo('<?php echo $val2->id;?>',$(this))"><em class="<?php echo $val2->ico;?>"></em><?php echo $val2->title;?></div>
		<ul class="left_list" id="menuThree_<?php echo $val2->id;?>">
<?php foreach (@$val2->menus as $val2) {
	$an = $val2->id==$this->Cid?'left_an1':'left_an2'; 
?>
			<li><a href="<?php echo base_url($val2->url.'.html');?>" class="<?php echo $an;?>"><em class="<?php echo $val2->ico;?>"></em><?php echo $val2->title;?></a></li>
<?php }?>
		</ul>
<?php }?>
<?php }}?>
		<div class="left_copy"><?php echo date('Y');?> &copy; <?php echo $this->config->config['copy'];?></div>
	</aside>
	<section class="ct_right">

<?php echo $this->getContent() ?>

	</section>
</section>
<div id="base_url" style="display: none;"><?php echo base_url();?></div>
<div id="IsMobile" style="display: none;"></div>
<?php echo $this->tag->javascriptInclude("../webmis/plugin/jquery/".JQUERY_NAME);?>
<?php echo $this->tag->javascriptInclude("../webmis/jquery.webmis.js");?>
<?php echo $this->tag->javascriptInclude("../themes/admin/".APP_THEMES."/main.js");?>
<?php if(@$js){ foreach($js as $val){ ?>
<script language="javascript" src="<?php echo base_url('views/'.$val); ?>"></script>
<?php }}?>
</body>
</html>