<form action="<?php echo $this->url->get('SysChangePasswd/Data');?>" method="post" id="Form">
<table class="table_add">
	<tr>
		<td colspan="2"><h2><?php echo $Menus['Ctitle'];?></h2></td>
	</tr>
	<tr>
		<td class="tright" width="60"></td>
		<td id="textVal"><span class="c2"><?php echo $incLang->_('inc_form_info');?></span></td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_pwd_uname');?>:</td>
		<td>
			<b id="uname"><?php echo @$_SESSION['Admin']['uname']; ?></b>
			<input type="hidden" name="uname" value="<?php echo @$_SESSION['AdminInfo']['uname']; ?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_pwd_pwd');?>:</td>
		<td>
			<input type="password" name="password" class="input" style="width: 180px;" rangelength="[6,16]" required />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_pwd_pwd1');?>:</td>
		<td>
			<input type="password" id="passwd" name="passwd" class="input" style="width: 180px;" rangelength="[6,16]" required />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_pwd_pwd2');?>:</td>
		<td>
			<input type="password" class="input" style="width: 180px;" equalTo="#passwd" required />
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td class="sub">
			<input type="submit" id="changeSub" value="<?php echo $Lang->_('sys_pwd_change');?>" />
		</td>
	</tr>
</table>
</form>
<br/><br/>