<form action="<?php echo $this->url->get('ClassWeb/Data/add');?>" method="post" id="Form">
<table class="table_add">
	<tr>
		<td class="tright" width="90"></td>
		<td id="textVal"><span class="c2"><?php echo $incLang->_('inc_form_info');?></span></td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_class');?>:</td>
		<td>
			<div id="newsClass">&nbsp;</div>
			<input type="hidden" id="menus_fid" name="fid" value="0" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_title');?>:</td>
		<td>
			<input type="text" name="title" class="input" style="width: 60%;" rangelength="[2,16]" required />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_en');?>:</td>
		<td>
			<input type="text" name="en" class="input" style="width: 60%;" rangelength="[2,16]" required />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_url');?>:</td>
		<td>
			<input type="text" name="url" class="input" style="width: 60%;" rangelength="[2,64]" required />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_ico');?>:</td>
		<td>
			<input type="text" name="ico" class="input" style="width: 60px;" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_remark');?>:</td>
		<td>
			<textarea name="remark" style="width: 95%; height: 80px;"></textarea>
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_sort');?>:</td>
		<td>
			<input type="text" name="sort" class="input" value="0" style="width: 60px;" />
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td class="sub">
			<input type="submit" id="Sub" value="<?php echo $incLang->_('inc_add');?>" />
		</td>
	</tr>
</table>
</form>