<form action="<?php echo $this->url->get('ClassWeb/Data/audit');?>" method="post" id="Form">
<table class="table_add">
	<tr>
		<td class="tright" width="80"><?php echo $Lang->_('class_web_state');?>:</td>
		<td>
			<select name="state">
				<option value="0"><?php echo $incLang->_('inc_nopass');?></option>
				<option value="1"><?php echo $incLang->_('inc_pass');?></option>
			</select>
		</td>
	</tr>
	<tr>
		<td class="sub center" colspan="2">
			<input type="submit" id="Sub" value="<?php echo $incLang->_('inc_save');?>" />
			<input type="hidden" id="DelID" name="id" value="" />
		</td>
	</tr>
</table>
</form>