<form action="<?php echo $this->url->get('ClassWeb/Data/edit');?>" method="post" id="Form">
<table class="table_add">
	<tr>
		<td class="tright" width="90"></td>
		<td id="textVal"><span class="c2"><?php echo $incLang->_('inc_form_info');?></span></td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_class');?>:</td>
		<td>
			<input type="text" id="menus_fid" name="fid" class="input" style="width: 40px;" value="<?php echo $Edit->fid;?>" />
			<span id="newsClass">&nbsp;</span>
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_title');?>:</td>
		<td>
			<input type="text" name="title" class="input" style="width: 60%;" value="<?php echo $Edit->title;?>" rangelength="[2,16]" required />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_en');?>:</td>
		<td>
			<input type="text" name="en" class="input" style="width: 60%;" value="<?php echo $Edit->en;?>" rangelength="[2,16]" required />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_url');?>:</td>
		<td>
			<input type="text" name="url" class="input" style="width: 60%;" value="<?php echo $Edit->url;?>" rangelength="[2,64]" required />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_ico');?>:</td>
		<td>
			<input type="text" name="ico" class="input" style="width: 60px;" value="<?php echo $Edit->ico;?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_remark');?>:</td>
		<td>
			<textarea name="remark" style="width: 95%; height: 80px;"><?php echo $Edit->remark;?></textarea>
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_sort');?>:</td>
		<td>
			<input type="text" name="sort" class="input" value="<?php echo $Edit->sort;?>" style="width: 60px;" />
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td class="sub">
			<input type="hidden" name="id" value="<?php echo $Edit->id;?>" />
			<input type="submit" id="Sub" value="<?php echo $incLang->_('inc_edit');?>" />
		</td>
	</tr>
</table>
</form>