<form action="<?php echo $this->url->get('ClassWeb/Data/edit');?>" method="post" id="Form">
<table class="table_add">
	<tr>
		<td class="width tright"><?php echo $Lang->_('class_web_class');?>:</td>
		<td>
			<input type="text" id="menus_fid" name="fid" class="input" style="width: 40px;" value="<?php echo $Edit->fid;?>" />
			<span id="newsClass">&nbsp;</span>
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_title');?>:</td>
		<td>
			<input type="text" name="title" class="input" style="width: 60%;" value="<?php echo $Edit->title;?>" datatype="*2-16" errormsg="2~16<?php echo $incLang->_('inc_form_char');?>" sucmsg="<?php echo $incLang->_('inc_form_pass');?>" nullmsg="<?php echo $incLang->_('inc_form_null');?>" />
			<span class="Validform_checktip"></span>
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_url');?>:</td>
		<td>
			<input type="text" name="url" class="input" style="width: 60%;" value="<?php echo $Edit->url;?>" datatype="*2-32" errormsg="2~32<?php echo $incLang->_('inc_form_char');?>" sucmsg="<?php echo $incLang->_('inc_form_pass');?>" nullmsg="<?php echo $incLang->_('inc_form_null');?>" />
			<span class="Validform_checktip"></span>
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_ico');?>:</td>
		<td>
			<input type="text" name="ico" class="input" style="width: 60px;" value="<?php echo $Edit->ico;?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_remark');?>:</td>
		<td>
			<textarea name="remark" style="width: 95%; height: 120px;"><?php echo $Edit->remark;?></textarea>
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_sort');?>:</td>
		<td>
			<input type="text" name="sort" class="input" value="<?php echo $Edit->sort;?>" style="width: 60px;" />
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td class="sub">
			<input type="hidden" name="id" value="<?php echo $Edit->id;?>" />
			<input type="submit" id="Sub" value="<?php echo $incLang->_('inc_edit');?>" />
		</td>
	</tr>
</table>
</form>