<form action="<?php echo $this->url->get('ClassWeb/index');?>" method="get">
<table class="table_add">
	<tr>
		<td class="tright" width="90">FID:</td>
		<td>
			<input type="text" name="fid" class="input" style="width: 30%;" value="<?php echo @$_GET['fid'];?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_title');?>:</td>
		<td>
			<input type="text" name="title" class="input" style="width: 80%;" value="<?php echo @$_GET['title'];?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_url');?>:</td>
		<td>
			<input type="text" name="url" class="input" style="width: 80%;" value="<?php echo @$_GET['url'];?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_ico');?>:</td>
		<td>
			<input type="text" name="ico" class="input" style="width: 30%;" value="<?php echo @$_GET['ico'];?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('class_web_remark');?>:</td>
		<td>
			<input type="text" name="remark" class="input" style="width: 80%;" value="<?php echo @$_GET['remark'];?>" />
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td class="sub">
			<input type="submit" id="seaSub" name="search" value="<?php echo $incLang->_('inc_sea');?>" />
		</td>
	</tr>
</table>
</form>