<form action="<?php echo $this->url->get('SysAdmin/Data/edit');?>" method="post" id="Form">
<table class="table_add">
	<tr>
		<td class="tright" width="90"><?php echo $Lang->_('sys_admin_state');?>:</td>
		<td>
			<select name="state">
				<option value="1" <?php echo $Edit->state==1?'':'selected';?> ><?php echo $Lang->_('sys_admin_enable');?></option>
				<option value="2" <?php echo $Edit->state==2?'selected':'';?> ><?php echo $Lang->_('sys_admin_disable');?></option>
			</select>
			<span class="1">&nbsp;</span>
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_admin_uname');?>:</td>
		<td>
			<?php echo $Edit->uname;?>
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_admin_npwd');?>:</td>
		<td>
			<input type="password" name="passwd" class="input" style="width: 80%;" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_admin_email');?>:</td>
		<td>
			<input type="text" name="email" class="input" value="<?php echo $Edit->email;?>" style="width: 80%;" datatype="e" errormsg="<?php echo $incLang->_('inc_form_format');?>" sucmsg="<?php echo $incLang->_('inc_form_pass');?>" nullmsg="<?php echo $incLang->_('inc_form_null');?>" />
			<span class="Validform_checktip"></span>
		</td>
	</tr>
	<tr>
		<td colspan="2"><b><?php echo $Lang->_('sys_admin_show');?></b></td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_admin_name');?>:</td>
		<td>
			<input type="text" name="name" class="input" style="width: 30%;" value="<?php echo $Edit->name;?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_admin_dept');?>:</td>
		<td>
			<input type="text" name="department" class="input" style="width: 60%;" value="<?php echo $Edit->department;?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_admin_position');?>:</td>
		<td>
			<input type="text" name="position" class="input" style="width: 60%;" value="<?php echo $Edit->position;?>" />
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td class="sub">
			<input type="hidden" name="id" value="<?php echo $Edit->id;?>" />
			<input type="submit" id="Sub" value="<?php echo $incLang->_('inc_edit');?>" />
		</td>
	</tr>
</table>
</form>