<form action="<?php echo $this->url->get('SysAdmin/index');?>" method="get">
<table class="table_add">
	<tr>
		<td class="tright" width="90"><?php echo $Lang->_('sys_admin_state');?>:</td>
		<td>
			<select name="state">
				<option value="">Select All</option>
				<option value="1"><?php echo $Lang->_('sys_admin_enable');?></option>
				<option value="2"><?php echo $Lang->_('sys_admin_disable');?></option>
			</select>
			<span class="1">&nbsp;</span>
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_admin_uname');?>:</td>
		<td>
			<input type="text" name="uname" class="input" style="width: 60%;" value="<?php echo @$_GET['uname'];?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_admin_email');?>:</td>
		<td>
			<input type="text" name="email" class="input" style="width: 80%;" value="<?php echo @$_GET['email'];?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_admin_tel');?>:</td>
		<td>
			<input type="text" name="tel" class="input" style="width: 80%;" value="<?php echo @$_GET['tel'];?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_admin_name');?>:</td>
		<td>
			<input type="text" name="name" class="input" style="width: 30%;" value="<?php echo @$_GET['name'];?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_admin_dept');?>:</td>
		<td>
			<input type="text" name="department" class="input" style="width: 60%;" value="<?php echo @$_GET['department'];?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_admin_position');?>:</td>
		<td>
			<input type="text" name="position" class="input" style="width: 60%;" value="<?php echo @$_GET['position'];?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_admin_rtime');?>:</td>
		<td>
			<input type="text" name="rtime" class="input" style="width: 60%;" value="<?php echo @$_GET['rtime'];?>" />
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td class="sub">
			<input type="submit" id="seaSub" name="search" value="<?php echo $incLang->_('inc_sea');?>" />
		</td>
	</tr>
</table>
</form>