<form action="<?php echo $this->url->get('SysDBBackup/Data/export');?>" method="post" id="Form">
<table class="table_add">
	<tr>
		<td class="tright" width="90"><?php echo $Lang->_('sys_db_backup_name');?>:</td>
		<td>
			<input type="text" name="name" class="input" style="width: 60%;" value="<?php echo $Fname;?>" datatype="*2-30" errormsg="2~30<?php echo $incLang->_('inc_form_char');?>" sucmsg="<?php echo $incLang->_('inc_form_pass');?>" nullmsg="<?php echo $incLang->_('inc_form_null');?>" />
			<span class="Validform_checktip"></span>
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_db_backup_format');?>:</td>
		<td>
			<select name="format">
				<option value="sql">.sql</option>
			</select>
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_db_backup_dir');?>:</td>
		<td>
			<select name="dir">
				<option value="<?php echo APP_BACKUP;?>"><?php echo APP_BACKUP;?></option>
			</select>
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_db_backup_table');?>:</td>
		<td>
			<textarea name="table" style="width: 95%; height: 160px;"><?php echo $Table;?></textarea>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td class="sub">
			<input type="submit" id="Sub" value="<?php echo $incLang->_('inc_export');?>" />
		</td>
	</tr>
</table>
</form>