<span class="action">
	<span class="title"><?php echo $Menus['Ctitle'];?></span>
<?php foreach ($Menus['action'] as $val){
	$url = $val['ico']=='ico-list'?$this->url->get($this->dispatcher->getControllerName()):'';
?>
	<a href="<?php echo $url;?>" id="<?php echo $val['ico'];?>"><em class="<?php echo $val['ico'];?>"></em><span><?php echo $val['name'];?></span></a>
<?php }?>
</span>
<!-- Content -->
<table class="table_list">
	<tr class="title">
		<td width="20"><a href="#" id="checkboxY"></a><a href="#" id="checkboxN"></a></td>
		<td><?php echo $Lang->_('sys_db_backup_table');?></td>
		<td><?php echo $Lang->_('sys_db_backup_field');?></td>
		<td><?php echo $Lang->_('sys_db_backup_num');?></td>
	</tr>
	<tbody id="listBG">
<?php foreach ($Tables as $val){?>
	<tr>
		<td><input type="checkbox" value="<?php echo $val['name'];?>" /></td>
		<td class="tleft"><?php echo $val['name'];?></td>
		<td class="tleft"><?php echo $val['field'];?></td>
		<td><?php echo $val['num'];?></td>
	</tr>
<?php }?>
	</tbody>
</table>
<!-- Content End -->