<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="ksphp" />
	<title>WebMIS信息提示</title>
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
	<link href="/themes/admin/<?php echo APP_THEMES;?>/error.css" rel="stylesheet" type="text/css" />
	<script>var _hmt = _hmt || [];(function() {var hm = document.createElement("script");hm.src = "//hm.baidu.com/hm.js?42c6e4ddf1d67ece9be84ce625cd398b";var s = document.getElementsByTagName("script")[0];s.parentNode.insertBefore(hm, s);})();</script>
</head>

<body>
<?php echo $this->getContent() ?>
</body>
</html>