<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="ksphp" />
	<title>信息提示 | WebMIS</title>
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
	<link href="/themes/admin/<?php echo APP_THEMES;?>/error.css" rel="stylesheet" type="text/css" />
</head>

<body>
<?php echo $this->getContent() ?>
</body>
</html>