<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
	<meta name="format-detection" content="telephone=no">
	<meta name="author" content="KSPHP" />
	<title><?php echo APP_TITLE;?></title>
	<link rel="shortcut icon" href="/themes/favicon.ico" type="image/x-icon" />
	<?php echo $this->tag->stylesheetLink("/webmis/themes/".WEBMIS_THEMES."/webmis.css");?>
	<?php echo $this->tag->stylesheetLink("/themes/admin/".APP_THEMES."/main_m.css");?>
</head>

<body class="body_login">
	<!--	Lang -->
	<div id="Lang" class="lang_ct">
		<?php echo $LangName;?>
		<ul class="lang">
<?php foreach ($LangAll as $key=>$val){?>
			<li><a href="<?php echo $this->url->get('?lang='.$key); ?>"><?php echo $key.' | '.$val;?></a></li>
<?php }?>
		</ul>
	</div>
	<!--	Longin -->
	<h1 id="webmisVersion" class="login_title">WebMIS</h1>
	<div class="login_body">
		<div class="login_ct">
			<div class="login">
				<div class="title"><?php echo $incLang->_('inc_uname');?>：</div>
				<div class="input_ct"><input type="text" id="uname" class="login_input" value="webmis" /></div>
				<div class="title"><?php echo $incLang->_('inc_passwd');?>：</div>
				<div class="input_ct"><input type="password" id="passwd" class="login_input" value="ksphp.com" /></div>
			</div>
			<div class="sub"><a href="#" id="adminLogin"><?php echo $incLang->_('inc_login');?></a></div>
		</div>
	</div>
	<div class="login_copy">
		Copyright © <?php echo APP_COPY;?> All rights are reserved.<br>
		<a href="<?php echo $this->url->get('../');?>" ><?php echo $incLang->_('inc_home');?></a>&nbsp;|&nbsp;
		<a href="<?php echo $this->url->get('?mode=pc');?>" ><?php echo $incLang->_('inc_pc');?></a>&nbsp;|&nbsp;
		<a href="<?php echo $this->url->get('?mode=mobile');?>" ><?php echo $incLang->_('inc_mobile');?></a>
	</div>
<div id="base_url" style="display: none;"><?php echo $this->url->get();?></div>
<div id="IsMobile" style="display: none;"><?php echo $this->session->get('IsMobile');?></div>
<div id="getLang" style="display: none;"><?php echo $this->session->get('Lang');?></div>
<?php echo $this->tag->javascriptInclude("/webmis/plugin/jquery/".JQUERY_NAME);?>
<?php echo $this->tag->javascriptInclude("/webmis/jquery.webmis.js");?>
<?php echo $this->tag->javascriptInclude("/themes/admin/".APP_THEMES."/login.js");?>
</body>
</html>
