<form action="<?php echo $this->url->get('SysDBRestore/Data/import');?>" method="post" id="Form">
<table class="table_add">
	<tr>
		<td class="tright" width="60"><?php echo $Lang->_('sys_db_restore_file');?>:</td>
		<td>
			<input type="text" name="file" class="input" style="width: 80%;" value="<?php echo $File;?>" />
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td class="c666"><?php echo $Lang->_('sys_db_restore_text');?></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td class="sub">
			<input type="submit" id="Sub" value="<?php echo $incLang->_('inc_import');?>" />
		</td>
	</tr>
</table>
</form>