<form action="<?php echo $this->url->get('SysMenusAction/Data/add');?>" method="post" id="Form">
<table class="table_add">
	<tr>
		<td class="tright" width="90"></td>
		<td id="textVal"><span class="c2"><?php echo $incLang->_('inc_form_info');?></span></td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_menu_a_name');?>:</td>
		<td>
			<input type="text" name="name" class="input" style="width: 70%;" rangelength="[2,32]" required />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_menu_a_perm');?>:</td>
		<td>
			<input type="text" id="action_perm" name="perm" class="input" style="width: 40%;" digits="true" maxlength="6" required />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_menu_a_icon');?>:</td>
		<td>
			<input type="text" name="ico" class="input" style="width: 40%;" rangelength="[2,24]" required />
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td class="sub">
			<input type="submit" id="Sub" value="<?php echo $incLang->_('inc_add');?>" />
		</td>
	</tr>
</table>
</form>