<form action="<?php echo $this->url->get('SysMenusAction/index');?>" method="get">
<table class="table_add">
	<tr>
		<td class="tright" width="90"><?php echo $Lang->_('sys_menu_a_name');?>:</td>
		<td>
			<input type="text" name="name" class="input" style="width: 80%;" value="<?php echo @$_GET['name'];?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_menu_a_perm');?>:</td>
		<td>
			<input type="text" name="perm" class="input" style="width: 80%;" value="<?php echo @$_GET['perm'];?>" />
		</td>
	</tr>
	<tr>
		<td class="tright"><?php echo $Lang->_('sys_menu_a_icon');?>:</td>
		<td>
			<input type="text" name="ico" class="input" style="width: 80%;" value="<?php echo @$_GET['ico'];?>" />
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td class="sub">
			<input type="submit" id="seaSub" name="search" value="<?php echo $incLang->_('inc_sea');?>" />
		</td>
	</tr>
</table>
</form>